<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="DESKTOP-1D6MK40" failures="1" tests="1" name="Default test" time="3.952" errors="0" timestamp="2024-02-19T12:01:45 IST">
  <testcase classname="com.Test.HomePageTest" name="linkedintest" time="1.597">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://twitter.com/saucelabs] but found [https://www.linkedin.com/company/sauce-labs/]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://twitter.com/saucelabs] but found [https://www.linkedin.com/company/sauce-labs/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.Test.HomePageTest.linkedintest(HomePageTest.java:94)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- linkedintest -->
  <testcase classname="com.Test.HomePageTest" name="facebooktest" time="0.0">
    <ignored/>
  </testcase> <!-- facebooktest -->
  <testcase classname="com.Test.HomePageTest" name="SideMenuTest" time="0.0">
    <ignored/>
  </testcase> <!-- SideMenuTest -->
  <testcase classname="com.Test.HomePageTest" name="RemoveTest" time="0.0">
    <ignored/>
  </testcase> <!-- RemoveTest -->
  <testcase classname="com.Test.HomePageTest" name="carttest" time="0.0">
    <ignored/>
  </testcase> <!-- carttest -->
  <testcase classname="com.Test.HomePageTest" name="twittertest" time="0.0">
    <ignored/>
  </testcase> <!-- twittertest -->
  <testcase classname="com.Test.HomePageTest" name="AddItemtest" time="0.0">
    <ignored/>
  </testcase> <!-- AddItemtest -->
</testsuite> <!-- Default test -->
