<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="6" total="7" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-02-19T12:01:41 IST" name="Default suite" finished-at="2024-02-19T12:01:45 IST" duration-ms="3952">
    <groups>
    </groups>
    <test started-at="2024-02-19T12:01:41 IST" name="Default test" finished-at="2024-02-19T12:01:45 IST" duration-ms="3952">
      <class name="com.Test.HomePageTest">
        <test-method is-config="true" signature="initdriver()[pri:0, instance:com.Test.HomePageTest@229c6181]" started-at="2024-02-19T12:01:41 IST" name="initdriver" finished-at="2024-02-19T12:01:43 IST" duration-ms="1971" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initdriver -->
        <test-method is-config="true" signature="testlogin()[pri:0, instance:com.Test.HomePageTest@229c6181]" started-at="2024-02-19T12:01:43 IST" name="testlogin" finished-at="2024-02-19T12:01:43 IST" duration-ms="345" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testlogin -->
        <test-method signature="linkedintest()[pri:0, instance:com.Test.HomePageTest@229c6181]" started-at="2024-02-19T12:01:43 IST" name="linkedintest" finished-at="2024-02-19T12:01:45 IST" duration-ms="1597" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [https://twitter.com/saucelabs] but found [https://www.linkedin.com/company/sauce-labs/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://twitter.com/saucelabs] but found [https://www.linkedin.com/company/sauce-labs/]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.Test.HomePageTest.linkedintest(HomePageTest.java:94)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- linkedintest -->
      </class> <!-- com.Test.HomePageTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
